### ISSUE TITLE
Show aggregated data for states or entire Germany

### ISSUE THREAD

**Issue by ndeuma** [ndeuma/covid19-casedata#9]
Right now, the API allows only queries for individual counties.

**Comment by ndeuma** [comment]
Implemented with 02f1c3d4fcd81443ab78f4821e9771baaf3804c5 (states, using @jgehrcke 's API) and 9990aa2aa4563b18f45daf671cebc8d30ab95f55 (Germany, manually entered data)

**Comment by jgehrcke** [comment]
@ndeuma thanks for the mention, it's cool follow what others do. If you'd like to see any further API changes please let me know!
